### PR TITLE
fix: Structured Comment Exploration

### LINKED ISSUE #48: ```diff
```diff
! No answer from OpenAI
```

_Originally posted by @ubiquity-os-beta[bot] in https://github.com/ubiquity-os-marketplace/text-vector-embeddings/issues/67#issuecomment-2577541987_
            

## What happened

The `/ask` command failed to run, due to a context being too large, thus failing with
```json
{
       "res": {
         "error": {
           "message": "Provider returned error",
           "code": 400,
           "metadata": {
             "raw": "{\n  \"error\": {\n    \"message\": \"This model's maximum context length has been exceeded. Please reduce the length of the messages.\",\n    \"type\": \"invalid_request_error\",\n    \"param\": \"messages\",\n    \"code\": \"context_length_exceeded\"\n  }\n}",
             "provider_name": "OpenAI"
           }
         },
         "user_id": "user_2njZil2BmAzm3iDZvVsx69KWg4A"
       },
       "caller": "Completions.createCompletion"
     }
```

Multiple problems here:

- it should use `postComment` so we get the run url and the proper error stack
- there should not be two comments for the failure
- the context should be truncated in some way to allow `/ask` to run properly

## What was expected

`/ask` should truncate the context so it runs properly and still gives an accurate answer.

## How to reproduce

The easiest would probably to run `/ask` against the aforementioned issue, or create an issue with a very long content.

### PR DESCRIPTION
**Pull request by shiv810**
Resolves #48 

- [X] Control the depth, with which you want to explore new issues
- [X]  Remove Elements from nodes if exceeding the context limit.

### CODE REVIEW

File: src/handlers/ask-llm.ts [hunk 1]
```diff
@@ -49,6 +55,8 @@ export async function askLlm(context: Context, question: string, formattedChat:
       ...(similarIssues?.map((issue: IssueSimilaritySearchResult) => issue.issue_plaintext) || []),
     ];
 
+    context.logger.info("Similar text: " + similarText.join("\n"));
```
Comment (gentlementlegen) [inline src/handlers/ask-llm.ts:58]: Wouldn't these logs be `debug` instead of `info`?

File: src/types/plugin-input.ts [hunk 2]
```diff
@@ -12,6 +12,7 @@ export const pluginSettingsSchema = T.Object({
   model: T.String({ default: "o1-mini" }),
   openAiBaseUrl: T.Optional(T.String()),
   similarityThreshold: T.Number({ default: 0.9 }),
+  maxDepth: T.Optional(T.Number({ default: 3 })),
```
Comment (gentlementlegen) [inline src/types/plugin-input.ts:15]: Would be nice to have a description here

File: src/helpers/format-chat-history.ts [hunk 3]
```diff
@@ -1,208 +1,377 @@
...
+  const numberRefs = body.match(/(?:^|\s)#(\d+)(?:\s|$)/g) || [];
+  for (const ref of numberRefs) {
+    const number = ref.trim().substring(1);
+    if (/^\d+$/.test(number)) {
+      const key = `${owner}/${repo}/${number}`;
+      addValidReference(key);
+    }
+  }
+
+  const resolveRefs = body.match(/(?:Resolves|Closes|Fixes)\s+#(\d+)/gi) || [];
```
Comment (gentlementlegen) [inline src/helpers/format-chat-history.ts:100]: This seems dangerous and lead to issues before, like in the following scenarios:
- multiple closing PRs
- this content located in the comment of the body
- this content located in a reference to another comment, or within a code block
- after `#` there can be a number or a URL

File: src/helpers/issue-handling.ts [hunk 4]
```diff
@@ -1,17 +1,181 @@
...
+  }
+}
+
+export async function handleIssue(
+  params: FetchParams,
+  streamlinedComments: Record<string, StreamlinedComment[]>,
+  alreadySeen: Set<string>,
+  parentKey?: string,
+  tokenLimits?: TokenLimits
+): Promise<Record<string, StreamlinedComment[]> | void> {
```
Comment (gentlementlegen) [inline src/helpers/issue-handling.ts:92]: Seems strange to return either or Record or `void`, `null` might be more appropriate

File: src/helpers/pull-request-fetching.ts [hunk 5]
```diff
@@ -0,0 +1,241 @@
...
+
+  try {
+    // Fetch PR data including both types of comments
+    const prData = await octokit.graphql<PullRequestGraphQlResponse>(
+      `
+      query($owner: String!, $repo: String!, $number: Int!) {
+        repository(owner: $owner, name: $repo) {
+          pullRequest(number: $number) {
+            body
+            closingIssuesReferences(first: 10) {
```
Comment (gentlementlegen) [inline src/helpers/pull-request-fetching.ts:73]: Might be safer to go for `100` (which I believe is the limit)

File: src/helpers/pull-request-fetching.ts [hunk 6]
```diff
@@ -0,0 +1,241 @@
...
+                body
+                repository {
+                  owner {
+                    login
+                  }
+                  name
+                }
+              }
+            }
+            reviews(first: 100) {
```
Comment (gentlementlegen) [inline src/helpers/pull-request-fetching.ts:86]: Don't you need to use pagination for all of these, or you don't care about the whole content?

File: .vscode/settings.json
Comment (gentlementlegen) [inline .vscode/settings.json:1]: To be deleted

File: src/helpers/format-chat-history.ts (hunk 3 above)
Comment (gentlementlegen) [reply src/helpers/format-chat-history.ts:91]: If you think this has no side effect then that is fine. I mention this because in the body comment, as an example, we always quote "Resolves #1234" which will potentially link all the issues to the issue #1234 if there is any in the repository.

**Comment by 0x4007** [comment]
/ask based on the death help me understand what strategy was taken to solve the problem

**Comment by Keyrxng** [comment]
Nice to see `maxDepth` being implemented finally - one of the things I advocated for early on in development of this plugin but better late than never. gg

**Comment by 0x4007** [comment]
> > ```diff
> 
> > ! An error occurred
> 
> > ```
> 
> 
> 
> The Openrouter account has run out of credits and needs to be topped up.

Can we coordinate to fix this? As I understand it's your account but let's use my account instead and I can handle paying for it?

File: src/types/llm.ts [hunk 7]
```diff
@@ -33,7 +34,7 @@ export type GroundTruthsSystemMessageTemplate = {
 };
 
 export type StreamlinedComment = {
-  id: number;
+  id: string | number;
```
Comment (0x4007) [inline src/types/llm.ts:37]: Why string and number? Seems wrong

File: src/types/github-types.ts [hunk 8]
```diff
@@ -1,26 +1,88 @@
...
 };
 
-export type LinkedIssues = {
+type IssueCommentNode = {
+  id: string;
+  body: string;
+  issue: IssueData;
+};
+
+export type GqlIssueSearchResult = {
```
Comment (0x4007) [inline src/types/github-types.ts:55]:
```suggestion
export type GraphQlIssueSearchResult = {
```

I would write out the full term to reduce cognitive overhead.

File: src/plugin.ts [hunk 9]
```diff
@@ -4,7 +4,7 @@ import { createClient } from "@supabase/supabase-js";
 import { VoyageAIClient } from "voyageai";
 import OpenAI from "openai";
```
Comment (0x4007) [inline src/plugin.ts:5]: Shouldn't we be using open router? I wonder if we should use Claude instead perhaps we should compare outputs.

**Review by 0x4007 — APPROVED** [review]
QA seems fine

**Comment by gentlementlegen** [comment]
@shiv810 
image

**Comment by gentlementlegen** [comment]
@shiv810 That was the related run correct? https://github.com/ubiquity-os-marketplace/command-ask/actions/runs/12879810114/job/35907862016
