### PR TITLE
fix: tip on thinking msg and prrc posting

### LINKED ISSUE #66: "Thinking" Adjustments
> UbiquityOS is thinking... [^04^]

Thinking is not posted in the [review thread](https://github.com/ubiquity-os-marketplace/personal-agent/pull/1#discussion_r1948903492). [^03^] [^02^] [^01^] Also should have the tip syntax:
> [!TIP]
> Syntax

---

> [!Caution]
> 
> No answer from OpenAI

@shiv810 can you address these [^05^] 

[^01^]: ⚠ 75% possible duplicate - [Missing context](https://www.github.com/ubiquity-os-marketplace/command-ask/issues/26#26)

[^02^]: ⚠ 75% possible duplicate - [The command `/ask` fails on large contexts](https://www.github.com/ubiquity-os-marketplace/command-ask/issues/48#48)

[^03^]: ⚠ 76% possible duplicate - [Doesn't work in pull request review](https://www.github.com/ubiquity-os-marketplace/command-ask/issues/29#29)

[^04^]: ⚠ 77% possible duplicate - [Improve User Experience](https://www.github.com/ubiquity-os-marketplace/command-ask/issues/52#52)

[^05^]: ⚠ 78% possible duplicate - [Context window formatting](https://www.github.com/ubiquity-os-marketplace/command-ask/issues/16#16)

### PR DESCRIPTION
**Pull request by shiv810**
Resolves #66

- Adds `TIP` on thinking message.

### CODE REVIEW

**Comment by shiv810** [comment]
QA:

- [Pull Request Review Comment](https://github.com/ShivTestOrg/test-public/pull/208#discussion_r1955544324)

File: src/handlers/comment-created-callback.ts [hunk 1]
```diff
@@ -22,7 +22,25 @@ export async function processCommentCallback(context: Context<"issue_comment.cre
...
+          inReplyTo: {
+            commentId: isPullRequestReviewComment ? payload.comment.id : undefined,
+          },
+        }
+      : undefined;
+
+    await addCommentToIssue(
+      context,
+      `> [!TIP]
+> ${env.UBIQUITY_OS_APP_NAME} is thinking...`,
```
Comment (0x4007) [inline src/handlers/comment-created-callback.ts:40]:
```suggestion
> Thinking...`,
```

Comment (0x4007) [reply src/handlers/comment-created-callback.ts:40]: We should replicate ChatGPT UI. Maybe we can including a tiny loading gif of sorts. 

It's redundant to put their name juxtaposed right next to their display name

File: tests/log.test.ts [hunk 2]
```diff
@@ -31,6 +31,11 @@ describe("Log post message test", () => {
     } as never;
 
     await processCommentCallback(context);
-    expect(addCommentToIssue).toHaveBeenCalledWith(expect.anything(), "UbiquityOS is thinking...");
+    expect(addCommentToIssue).toHaveBeenCalledWith(
+      expect.anything(),
+      `> [!TIP]
+> UbiquityOS is thinking...`,
```
Comment (0x4007) [inline tests/log.test.ts:37]:
```suggestion
> Thinking...`,
```

File: src/handlers/comment-created-callback.ts (hunk 1 above)
Comment (0x4007) [reply src/handlers/comment-created-callback.ts:40]: /ask previously I discussed mapping the GitHub flavored syntax against http status codes. For example !TIP to 2xx and !CAUTION to 5xx. Can you list what would map to http status code for redirection? The idea of writing "thinking" suggests that it's a like a redirect or even better but a "processing" response which already has a standardized status code. I want to use our mapping for this.

**Comment by 0x4007** [comment]
> > [!CAUTION]
> > Not Found - https://docs.github.com/rest/pulls/comments#update-a-review-comment-for-a-pull-request
> 

Looks like it can't edit a review comment.

File: src/handlers/comment-created-callback.ts (hunk 1 above)
Comment (0x4007) [reply src/handlers/comment-created-callback.ts:40]: `202` seems accurate so let's use !TIP

**Review by 0x4007 — APPROVED** [review]
If I was able to commit my suggestions I would have and merged so please do so. 

We can think on the loading gif idea another time.
