### PR TITLE
fix: ignore file path and diffs

### LINKED ISSUE #19: Payload optimization
This is an example of a diff q&a gone bad. Too much was sent to the model and it was rate limited. Below describes a dynamic strategy that should be simple to implement and should intelligently include only the most relevant changes. 

https://github.com/ubiquity-os-marketplace/text-conversation-rewards/pull/163#issuecomment-2439995967

### PR DESCRIPTION
**Pull request by sshivaditya2019**
Resolves #19

- Introduces a method to selectively retrieve diffs.
- Allows for the exclusion of files based on their directory and file extensions.

### CODE REVIEW

File: src/helpers/issue-fetching.ts [hunk 1]
```diff
@@ -167,15 +168,18 @@ export async function mergeCommentsAndFetchSpec(
...
-      mediaType: {
-        format: "diff",
-      },
+    const githubDiff = new GithubDiff(octokit);
+    //Fetch the statistics of the pull request
+    const stats = await githubDiff.getPullRequestStats(org, repo, issue);
+    //Find the filenames which do not have more than 200 changes
+    let files = stats.filter((file) => file.changes < 500).map((file) => file.filename);
+    //Ignore files like in dist or build or .lock files
+    const ignoredFiles = ["dist/*", "build/*", ".lock", "index.js"];
```
Comment (0x4007) [inline src/helpers/issue-fetching.ts:177]: Should definitely be dynamic from git ignore and such. Otherwise this was not included in the spec.

File: src/helpers/issue-fetching.ts [hunk 2]
```diff
@@ -167,15 +168,18 @@ export async function mergeCommentsAndFetchSpec(
...
-      repo,
-      pull_number: issue,
-      mediaType: {
-        format: "diff",
-      },
+    const githubDiff = new GithubDiff(octokit);
+    //Fetch the statistics of the pull request
+    const stats = await githubDiff.getPullRequestStats(org, repo, issue);
+    //Find the filenames which do not have more than 200 changes
+    let files = stats.filter((file) => file.changes < 500).map((file) => file.filename);
```
Comment (0x4007) [inline src/helpers/issue-fetching.ts:175]: Wrong approach. Should not be any hard cut off from some arbitrary number. Follow the spec

**Review by 0x4007 — CHANGES_REQUESTED** [review]

File: src/helpers/format-chat-history.ts [hunk 3]
```diff
@@ -83,7 +88,18 @@ async function createContextBlockSection(
   if (!issueNumber || isNaN(issueNumber)) {
     throw context.logger.error("Issue number is not valid");
   }
-  const prDiff = await fetchPullRequestDiff(context, org, repo, issueNumber);
+  const pulls = await fetchLinkedPrFromIssue(org, repo, issueNumber, context);
```
Comment (Keyrxng) [inline src/helpers/format-chat-history.ts:91]: These `pulls` rely on searching the repo for all PRs then parsing the PR bodies for a `#<issueNumber>`, which is recommended but not enforced so this isn't 100% reliable. We tend to use GQL API for this nowadays as it's most reliable. Also for queries that potentially return more than 100 items we should use `octokit.paginate(octokit.pulls.list))` as when scanning all PRs it's likely.

It's also relying on the PR author actually linking using `#` because if they copy paste the url which most do then it'll be a url in the pr body instead. I had logic for hashtag + url matching in my implementation but I think you may have removed it.

I think it may also be pulling more PR diffs than intended within this promise on each call to `createContextBlockSection`, unsure without QA-ing and inspecting the formatted chat on a context rich repo.

File: package.json [hunk 4]
```diff
@@ -17,7 +17,7 @@
     "knip-ci": "knip --no-exit-code --reporter json --config .github/knip.ts",
     "prepare": "husky install",
     "test": "jest --setupFiles dotenv/config --coverage",
-    "worker": "wrangler dev --env dev --port 4000"
+    "worker": "wrangler dev --env dev --port 5000"
```
Comment (Keyrxng) [inline package.json:20]: Is there a specific reason that you change this? The template uses `:4000` so all other plugins also, it's tedious having to change it back for no reason

File: src/adapters/openai/helpers/completions.ts [hunk 5]
```diff
@@ -2,6 +2,7 @@ import OpenAI from "openai";
 import { Context } from "../../../types";
 import { SuperOpenAi } from "./openai";
 import { CompletionsModelHelper, ModelApplications } from "../../../types/llm";
+import { encode } from "gpt-tokenizer";
 const MAX_TOKENS = 7000;
```
Comment (Keyrxng) [inline src/adapters/openai/helpers/completions.ts:6]: should move this into `config` and pass this via the yml config

File: src/helpers/format-chat-history.ts [hunk 6]
```diff
@@ -1,8 +1,9 @@
 import { Context } from "../types";
 import { StreamlinedComment, StreamlinedComments } from "../types/llm";
 import { createKey, streamlineComments } from "../handlers/comments";
-import { fetchPullRequestDiff, fetchIssue, fetchIssueComments } from "./issue-fetching";
+import { fetchPullRequestDiff, fetchIssue, fetchIssueComments, fetchLinkedPrFromIssue } from "./issue-fetching";
 import { splitKey } from "./issue";
+const MAX_TOKENS_ALLOWED = 7000;
```
Comment (Keyrxng) [inline src/helpers/format-chat-history.ts:6]: Same here. Should also be renamed to `MAX_COMPLETION_TOKENS`.

File: src/helpers/issue-fetching.ts [hunk 7]
```diff
@@ -164,18 +165,40 @@ export async function mergeCommentsAndFetchSpec(
...
-      repo,
-      pull_number: issue,
-      mediaType: {
-        format: "diff",
-      },
-    });
-    return data as unknown as string;
+    const githubDiff = new GithubDiff(octokit);
+    //Fetch the statistics of the pull request
+    const stats = await githubDiff.getPullRequestStats(org, repo, issue);
```
Comment (Keyrxng) [inline src/helpers/issue-fetching.ts:173]: This lib is only called twice and can be done just as simply with one or two rest calls I'm sure, it's not clear if this is ideal relying on a lib for this. Nothing to hold back the PR for just an observation.

File: src/helpers/issue-fetching.ts [hunk 8]
```diff
@@ -296,3 +318,41 @@ function castCommentsToSimplifiedComments(comments: Comments, params: FetchParam
       url: comment.html_url,
     }));
 }
+
+export async function fetchLinkedPrFromIssue(owner: string, repo: string, issueNumber: number, context: Context) {
+  const prs = await context.octokit.rest.pulls.list({
```
Comment (Keyrxng) [inline src/helpers/issue-fetching.ts:323]: Might be best to wrap this in a try-catch because if e.g the repo has been deleted this will likely throw

File: src/helpers/issue-fetching.ts [hunk 9]
```diff
@@ -296,3 +318,41 @@ function castCommentsToSimplifiedComments(comments: Comments, params: FetchParam
       url: comment.html_url,
     }));
 }
+
+export async function fetchLinkedPrFromIssue(owner: string, repo: string, issueNumber: number, context: Context) {
```
Comment (Keyrxng) [inline src/helpers/issue-fetching.ts:322]: Could be better named as it's actually fetching the linked issue from the pull request body

File: src/helpers/issue-fetching.ts [hunk 10]
```diff
@@ -296,3 +318,41 @@ function castCommentsToSimplifiedComments(comments: Comments, params: FetchParam
...
+  const prs = await context.octokit.rest.pulls.list({
+    owner: owner,
+    repo: repo,
+    state: "all",
+  });
+  //Filter the PRs which are linked to the issue using the body of the PR
+  return prs.data.filter((pr) => pr.body?.includes(`#${issueNumber}`));
```
Comment (Keyrxng) [inline src/helpers/issue-fetching.ts:329]: Might be best to add handling for url matching too

File: package.json (hunk 4 above)
Comment (Keyrxng) [reply package.json:20]: The plugin-template comes with `:4000` as standard so it's habitual for plugin devs to copy paste that url into `-config.yml` and expecting it to work thinking something is broken for it to be the dev port lmao.

Ideally don't commit it if you want to use another port, like running multiple plugins locally for example, always change it back to the template port if you can remember to.

File: src/helpers/issue-fetching.ts [hunk 11]
```diff
@@ -164,18 +165,40 @@ export async function mergeCommentsAndFetchSpec(
...
-      mediaType: {
-        format: "diff",
-      },
-    });
-    return data as unknown as string;
+    const githubDiff = new GithubDiff(octokit);
+    //Fetch the statistics of the pull request
+    const stats = await githubDiff.getPullRequestStats(org, repo, issue);
+    //Ignore files like in dist or build or .lock files
+    const ignoredFiles = (await buildIgnoreFilesFromGitIgnore(context, org, repo)) || [];
```
Comment (0x4007) [inline src/helpers/issue-fetching.ts:175]: Hey i just realized this is pointless. 

If its ignored it wont be on git or on the diff. Remove all this logic and just rely on filtering files out based on largest amount of changes to smallest.

File: src/helpers/issue-fetching.ts [hunk 12]
```diff
@@ -296,3 +318,68 @@ function castCommentsToSimplifiedComments(comments: Comments, params: FetchParam
...
+}
+
+async function buildIgnoreFilesFromGitIgnore(context: Context, owner: string, repo: string): Promise<string[] | null> {
+  try {
+    const gitignore = await context.octokit.rest.repos.getContent({
+      owner,
+      repo,
+      path: ".gitignore",
+    });
+    // Build an array of files to ignore
```
Comment (0x4007) [inline src/helpers/issue-fetching.ts:366]: Get rid of all this logic too

**Review by 0x4007 — CHANGES_REQUESTED** [review]
Perhaps my spec isnt clear but youre not following it. 

- Remove all the file ignores. 
- Count amount of changes per file. 
- sort in order of amount of changes
- filter out files from most changes to least based on context limits. 

This will automatically filter out large automated changes like compiled dist and lock files.

**Comment by 0x4007** [comment]
> Basically this strategy would start by excluding dist and likely other large changes like lock file etc. 

This could have been worded better. I meant that it would automatically exclude those based on how large their diffs are. 

GitHub pull request code view UI handles this in a smart way, where it wont display the dist/index.js and lock files due to "large diffs" 

Perhaps they also have a line length limitation. It may be wise to replicate.

**Comment by 0x4007** [comment]
Alright so then it seems clear to me that we can measure the diff size in bytes and then go from there.

File: src/helpers/issue-fetching.ts (hunk 1 above)
Comment (gentlementlegen) [reply src/helpers/issue-fetching.ts]: Does it combine this + gitignore?

File: src/helpers/issue-fetching.ts (hunk 2 above)
Comment (0x4007) [reply src/helpers/issue-fetching.ts]: Max i guess config so that partners can budget their token use.

**Comment by 0x4007** [comment]
I think that's all you need to do. What is the problem?

File: src/types/plugin-inputs.ts [hunk 13]
```diff
@@ -23,6 +23,7 @@ export const pluginSettingsSchema = T.Object({
   model: T.String({ default: "o1-mini" }),
   openAiBaseUrl: T.Optional(T.String()),
   similarityThreshold: T.Number({ default: 0.9 }),
+  maxTokens: T.Number({ default: 10000 }),
```
Comment (0x4007) [inline src/types/plugin-inputs.ts:26]: Default should be the max for the model we are using? 10k seems arbitrary.
