### PR TITLE
fix: skip plugin exec if question is missing

### LINKED ISSUE #53: `Question not provided` error.
The kernel is forwarding, all `pull_request_review.comments` without processing them, through command router, leading to the `Question Not Provided` error.

_Originally posted by @shiv810 in https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/218#issuecomment-2606251320_

### PR DESCRIPTION
**Pull request by shiv810**
Resolves #53

- Skip plugin exec if question is missing.

### CODE REVIEW

File: src/handlers/comment-created-callback.ts [hunk 1]
```diff
@@ -17,9 +17,9 @@ export async function processCommentCallback(context: Context<"issue_comment.cre
     question = command.parameters.question;
   } else if (payload.comment.body.trim().startsWith("/ask")) {
     question = payload.comment.body.trim().replace("/ask", "").trim();
-  }
-  if (!question) {
-    throw logger.error("No question provided");
+  } else if (!question) {
+    logger.info("No question found in comment. Skipping.");
```
Comment (0x4007) [inline src/handlers/comment-created-callback.ts:21]: Doesn't look like you ran the formatter.

File: tests/main.test.ts [hunk 2]
```diff
@@ -106,36 +111,41 @@ describe("Ask plugin tests", () => {
...
-      `                      Just another issue`,
-      "                  Comments: 1",
-      `                  └── issuecomment-4: ubiquity: Just a comment [#1](https://github.com/ubiquity/test-repo/issues/1)`,
+      "    └── Issue #2 (" + BASE_LINK + "2)",
+      "        Body:",
+      `            ${ISSUE_BODY_BASE} #3`,
+      "        Comments: 1",
+      `        ├── issue_comment-3: ubiquity: ${ISSUE_ID_3_CONTENT} [#3](${BASE_LINK}3)`,
       "",
     ].join("\n");
```
Comment (0x4007) [inline tests/main.test.ts:142]: Isn't it simpler to put the entire thing inside of a string literal?

**Review by 0x4007 — APPROVED** [review]
Generally looks fine

**Comment by 0x4007** [comment]
> QA:
> 
> [PR-Review Comment](https://github.com/ShivTestOrg/test-public/pull/208#discussion_r1930077006) 

This doesn't look like its answering in the review thread

> [Action Run](https://github.com/ShivTestOrg/command-ask/actions/runs/12984017381/job/36206179887)

This appears to be running twice

**Comment by 0x4007** [comment]
> > This appears to be running twice
> 
> 
> 
> https://github.com/ShivTestOrg/command-ask/actions/runs/12984618775/job/36207856834

Not sure how you fixed it without relevant code changes but okay.
