### PR TITLE
fix: a start message saying the bot is "thinking" is displayed

### LINKED ISSUE #52: Improve User Experience
It would be a small detail but whenever I use this plugin, I think that nothing happens because no comment gets posted right away but rather the whole execution has to finish before any feedback is sent to the user. A simple  "ubiquity-os is thinking..." message at the beginning would show the user the command worked and that something is going on, which I believe could greatly improve the user experience.

### PR DESCRIPTION
**Pull request by gentlementlegen**
Resolves #52

QA: https://github.com/Meniole/command-ask/issues/1#issuecomment-2620509301

I needed to add the capability to edit comments to this plugin. It should be using the SDK later on, but it required too much changes and fell out of scope of this issue.

### CODE REVIEW

**Comment by 0x4007** [comment]
> I needed to add the capability to edit comments to this plugin. It should be using the SDK later on, but it required too much changes and fell out of scope of this issue

To me it seems that it would be more important to standardize this across every plugin vs adding this custom capability. This is accruing tech debt. 

But the feature is nice to have and I suppose the code changes are fine. It just seems that very little of the changes are actually related to the spec.

**Comment by gentlementlegen** [comment]
@0x4007 I started at first but it implied a lot of changes that went far beyond the spec. Also, I guess you noticed https://github.com/ubiquity-os/plugin-sdk/issues/63 which will be handy to solve this as well, this is the only plugin so far that also will answer to comments in pull-request and pull-request reviews, which is not handled yet by the SDK `postComment`. Also, I did not want to touch it yet because the metadata is specific to be parsed later by the LLM it seems, so will have to carefully proceed. I can take care of it.

**Comment by gentlementlegen** [comment]
@0x4007 Any update?

**Review by shiv810 — APPROVED** [review]

File: src/handlers/add-comment.ts [hunk 1]
```diff
@@ -6,13 +6,17 @@ interface CommentOptions {
...
+  lastCommentId?: number;
+};
 /**
  * Add a comment to an issue or pull request
  * @param context - The context object containing environment and configuration details
  * @param message - The message to add as a comment
  * @param options - Optional parameters for pull request review comments
  */
-export async function addCommentToIssue(context: Context, message: string, options?: CommentOptions) {
+export const addCommentToIssue: PostComment = async function (context: Context, message: string, options?: CommentOptions) {
```
Comment (0x4007) [inline src/handlers/add-comment.ts:19]: Functions need to be named for stack traces and debugging. Our linter settings is supposed to catch this.

**Review by 0x4007 — CHANGES_REQUESTED** [review]

**Comment by 0x4007** [comment]
You can merge after 1. Naming the function and 2. Re enabling that linter settings

File: src/handlers/add-comment.ts (hunk 1 above)
Comment (gentlementlegen) [reply src/handlers/add-comment.ts]: It does but it is a warning not an error, so I changed it to trigger errors instead.

File: src/handlers/add-comment.ts [hunk 2]
```diff
@@ -81,3 +103,5 @@ export async function addCommentToIssue(context: Context, message: string, optio
     throw error;
   }
 }
+
+addCommentToIssue.lastCommentId = undefined as number | undefined;
```
Comment (0x4007) [inline src/handlers/add-comment.ts:107]:
```suggestion
addCommentToIssue.lastCommentId = null;
```

Setting to undefined seems really unusual. Why not null

Comment (gentlementlegen) [reply src/handlers/add-comment.ts]: https://github.com/ubiquity-os-marketplace/command-ask/pull/58/commits/e4fd90e25c2db5b48881705ce3d3f16bdf011b31

**Review by 0x4007 — APPROVED** [review]

**Comment by 0x4007** [comment]
Fox conflicts then merge @gentlementlegen
