### PR TITLE
Fix: Env::OPENROUTER_API_KEY

### LINKED ISSUE #8: env var fix
`OPENAI_API_KEY` is actually now `OPENROUTER_API_KEY` as far as I can tell

My OpenAI key failed to be authenticated but things worked after I used an OpenRouter key.

Refs to this env var should be updated and readme updated to let contributors know to use this.

### PR DESCRIPTION
**Pull request by sshivaditya2019**
Resolves #8 

- Adds support for OPENROUTER_API_KEY

### CODE REVIEW

File: src/plugin.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ export async function plugin(inputs: PluginInputs, env: Env) {
     apiKey: env.VOYAGEAI_API_KEY,
   });
   const openAiObject = {
-    apiKey: env.OPENAI_API_KEY,
+    apiKey: (inputs.settings.openAiBaseUrl && env.OPENROUTER_API_KEY) || env.OPENAI_API_KEY,
```
Comment (0x4007) [inline src/plugin.ts:20]: Are you checking it exists first and throwing an error?
